type EmojiEntry = {
    emoji: string;
    keywords: string[];
};

export const EMOJI_CATEGORIES: Record<string, EmojiEntry[]> = {
    'Smileys & People': [
        { emoji: '😀', keywords: ['grinning', 'face', 'smile', 'happy'] },
        { emoji: '😃', keywords: ['smiley', 'face', 'happy', 'joy'] },
        { emoji: '😄', keywords: ['smile', 'face', 'happy', 'joy', 'laugh'] },
        { emoji: '😁', keywords: ['grin', 'face', 'smile', 'happy'] },
        { emoji: '😆', keywords: ['laugh', 'face', 'happy', 'satisfied'] },
        { emoji: '😅', keywords: ['sweat', 'smile', 'relief', 'nervous'] },
        { emoji: '🤣', keywords: ['rofl', 'rolling', 'floor', 'laugh', 'funny'] },
        { emoji: '😂', keywords: ['joy', 'tears', 'laugh', 'cry', 'funny'] },
        { emoji: '🙂', keywords: ['slightly', 'smile', 'face', 'content'] },
        { emoji: '🙃', keywords: ['upside', 'down', 'silly', 'playful'] },
        { emoji: '😉', keywords: ['wink', 'flirt', 'playful', 'smile'] },
        { emoji: '😊', keywords: ['blush', 'smile', 'happy', 'shy'] },
        { emoji: '😇', keywords: ['innocent', 'angel', 'halo', 'good'] },
        { emoji: '🥰', keywords: ['hearts', 'love', 'affection', 'smile'] },
        { emoji: '😍', keywords: ['heart', 'eyes', 'love', 'crush'] },
        { emoji: '🤩', keywords: ['star', 'eyes', 'amazed', 'excited'] },
        { emoji: '😘', keywords: ['kiss', 'love', 'face', 'affection'] },
        { emoji: '😗', keywords: ['kiss', 'face', 'affection'] },
        { emoji: '😚', keywords: ['kiss', 'closed', 'eyes', 'affection'] },
        { emoji: '😙', keywords: ['kiss', 'smile', 'affection'] },
        { emoji: '😋', keywords: ['yum', 'delicious', 'food', 'smile'] },
        { emoji: '😛', keywords: ['tongue', 'playful', 'silly'] },
        { emoji: '😜', keywords: ['wink', 'tongue', 'playful', 'silly'] },
        { emoji: '🤪', keywords: ['crazy', 'zany', 'tongue', 'fun'] },
        { emoji: '😝', keywords: ['tongue', 'squint', 'playful', 'silly'] },
        { emoji: '🤑', keywords: ['money', 'greed', 'rich', 'face'] },
        { emoji: '🤗', keywords: ['hug', 'open', 'arms', 'affection'] },
        { emoji: '🤭', keywords: ['hand', 'mouth', 'oops', 'shy'] },
        { emoji: '🤫', keywords: ['shush', 'quiet', 'secret', 'silence'] },
        { emoji: '🤔', keywords: ['thinking', 'question', 'curious'] },
        { emoji: '🤐', keywords: ['zipper', 'mouth', 'secret', 'silence'] },
        { emoji: '🤨', keywords: ['raised', 'eyebrow', 'skeptical', 'doubt'] },
        { emoji: '😐', keywords: ['neutral', 'meh', 'indifferent'] },
        { emoji: '😑', keywords: ['expressionless', 'blank', 'face'] },
        { emoji: '😶', keywords: ['no', 'mouth', 'silent', 'mute'] },
        { emoji: '😏', keywords: ['smirk', 'suggestive', 'smile'] },
        { emoji: '😒', keywords: ['unamused', 'bored', 'annoyed'] },
        { emoji: '🙄', keywords: ['eyeroll', 'annoyed', 'sarcasm'] },
        { emoji: '😬', keywords: ['grimace', 'awkward', 'nervous'] },
        { emoji: '🤥', keywords: ['lying', 'nose', 'pinocchio', 'dishonest'] },
        { emoji: '😔', keywords: ['sad', 'pensive', 'down'] },
        { emoji: '😪', keywords: ['sleepy', 'tired', 'sleep'] },
        { emoji: '🤤', keywords: ['drool', 'hungry', 'sleepy'] },
        { emoji: '😴', keywords: ['sleep', 'zzz', 'tired'] },
        { emoji: '😷', keywords: ['mask', 'sick', 'ill', 'health'] },
        { emoji: '🤒', keywords: ['thermometer', 'sick', 'ill', 'fever'] },
        { emoji: '🤕', keywords: ['head', 'bandage', 'hurt', 'injury'] },
        { emoji: '🤢', keywords: ['nauseated', 'sick', 'ill', 'vomit'] },
        { emoji: '🤮', keywords: ['vomit', 'sick', 'ill', 'gross'] },
        { emoji: '🤧', keywords: ['sneeze', 'sick', 'ill', 'allergy'] },
        { emoji: '🥵', keywords: ['hot', 'overheated', 'sweat'] },
        { emoji: '🥶', keywords: ['cold', 'freezing', 'ice'] },
        { emoji: '🥴', keywords: ['woozy', 'dizzy', 'sick'] },
        { emoji: '😵', keywords: ['dizzy', 'dead', 'x', 'eyes'] },
        { emoji: '🤯', keywords: ['mind', 'blown', 'shock', 'amazed'] },
        { emoji: '🤠', keywords: ['cowboy', 'hat', 'western'] },
        { emoji: '🥳', keywords: ['party', 'celebrate', 'birthday'] },
        { emoji: '😎', keywords: ['cool', 'sunglasses', 'chill'] },
        { emoji: '🤓', keywords: ['nerd', 'glasses', 'geek'] },
        { emoji: '🧐', keywords: ['monocle', 'inspecting', 'curious'] },
        { emoji: '😕', keywords: ['confused', 'uncertain', 'puzzled'] },
        { emoji: '😟', keywords: ['worried', 'concerned', 'sad'] },
        { emoji: '🙁', keywords: ['frown', 'sad', 'unhappy'] },
        { emoji: '☹️', keywords: ['frown', 'sad', 'unhappy'] },
        { emoji: '😮', keywords: ['open', 'mouth', 'surprised'] },
        { emoji: '😯', keywords: ['hushed', 'surprised', 'quiet'] },
        { emoji: '😲', keywords: ['astonished', 'amazed', 'surprised'] },
        { emoji: '😳', keywords: ['flushed', 'embarrassed', 'shy'] },
        { emoji: '🥺', keywords: ['pleading', 'beg', 'sad', 'cute'] },
        { emoji: '😦', keywords: ['frown', 'open', 'mouth', 'sad'] },
        { emoji: '😧', keywords: ['anguished', 'distressed', 'sad'] },
        { emoji: '😨', keywords: ['fear', 'scared', 'worried'] },
        { emoji: '😰', keywords: ['anxious', 'cold', 'sweat', 'worried'] },
        { emoji: '😥', keywords: ['sad', 'disappointed', 'relieved'] },
        { emoji: '😢', keywords: ['cry', 'tear', 'sad'] },
        { emoji: '😭', keywords: ['cry', 'loud', 'tears', 'sad'] },
        { emoji: '😱', keywords: ['scream', 'fear', 'scared', 'shocked'] },
        { emoji: '😖', keywords: ['confounded', 'frustrated', 'upset'] },
        { emoji: '😣', keywords: ['persevere', 'struggling', 'sad'] },
        { emoji: '😞', keywords: ['disappointed', 'sad', 'down'] },
        { emoji: '😓', keywords: ['sweat', 'sad', 'disappointed'] },
        { emoji: '😩', keywords: ['weary', 'tired', 'exhausted'] },
        { emoji: '😫', keywords: ['tired', 'exhausted', 'overwhelmed'] },
        { emoji: '🥱', keywords: ['yawn', 'tired', 'sleepy'] },
        { emoji: '😤', keywords: ['triumph', 'angry', 'steam', 'nose'] },
        { emoji: '😡', keywords: ['angry', 'mad', 'annoyed'] },
        { emoji: '🤬', keywords: ['cursing', 'angry', 'swear', 'mad'] },
        { emoji: '😠', keywords: ['angry', 'mad', 'annoyed'] },
        { emoji: '🤯', keywords: ['mind', 'blown', 'shock', 'amazed'] },
        { emoji: '😈', keywords: ['smiling', 'devil', 'horns', 'evil'] },
        { emoji: '👿', keywords: ['angry', 'devil', 'horns', 'evil'] }
    ],
    'Animals & Nature': [
        { emoji: '🐶', keywords: ['dog', 'pet', 'animal', 'puppy'] },
        { emoji: '🐱', keywords: ['cat', 'pet', 'animal', 'kitten'] },
        { emoji: '🐭', keywords: ['mouse', 'animal', 'rodent'] },
        { emoji: '🐹', keywords: ['hamster', 'pet', 'animal'] },
        { emoji: '🐰', keywords: ['rabbit', 'bunny', 'animal', 'pet'] },
        { emoji: '🦊', keywords: ['fox', 'animal', 'wild'] },
        { emoji: '🐻', keywords: ['bear', 'animal', 'wild'] },
        { emoji: '🐼', keywords: ['panda', 'bear', 'animal'] },
        { emoji: '🐨', keywords: ['koala', 'bear', 'animal'] },
        { emoji: '🐯', keywords: ['tiger', 'cat', 'animal', 'wild'] },
        { emoji: '🦁', keywords: ['lion', 'animal', 'wild', 'king'] },
        { emoji: '🐮', keywords: ['cow', 'animal', 'farm'] },
        { emoji: '🐷', keywords: ['pig', 'animal', 'farm'] },
        { emoji: '🐽', keywords: ['pig', 'nose', 'animal'] },
        { emoji: '🐸', keywords: ['frog', 'animal', 'amphibian'] },
        { emoji: '🐵', keywords: ['monkey', 'animal', 'primate'] },
        { emoji: '🙈', keywords: ['see', 'no', 'evil', 'monkey'] },
        { emoji: '🙉', keywords: ['hear', 'no', 'evil', 'monkey'] },
        { emoji: '🙊', keywords: ['speak', 'no', 'evil', 'monkey'] },
        { emoji: '🐒', keywords: ['monkey', 'animal', 'primate'] },
        { emoji: '🐔', keywords: ['chicken', 'bird', 'animal', 'farm'] },
        { emoji: '🐧', keywords: ['penguin', 'bird', 'animal'] },
        { emoji: '🐦', keywords: ['bird', 'animal', 'flying'] },
        { emoji: '🐤', keywords: ['chick', 'bird', 'animal'] },
        { emoji: '🐣', keywords: ['hatching', 'chick', 'bird'] },
        { emoji: '🐥', keywords: ['front', 'facing', 'chick', 'bird'] },
        { emoji: '🦆', keywords: ['duck', 'bird', 'animal'] },
        { emoji: '🦅', keywords: ['eagle', 'bird', 'animal'] },
        { emoji: '🦉', keywords: ['owl', 'bird', 'animal', 'night'] },
        { emoji: '🦇', keywords: ['bat', 'animal', 'night'] },
        { emoji: '🐺', keywords: ['wolf', 'animal', 'wild'] },
        { emoji: '🐗', keywords: ['boar', 'animal', 'wild', 'pig'] },
        { emoji: '🐴', keywords: ['horse', 'animal', 'farm'] },
        { emoji: '🦄', keywords: ['unicorn', 'myth', 'horse', 'magic'] },
        { emoji: '🐝', keywords: ['bee', 'insect', 'honey'] },
        { emoji: '🐛', keywords: ['bug', 'insect', 'worm'] },
        { emoji: '🦋', keywords: ['butterfly', 'insect', 'animal'] },
        { emoji: '🐌', keywords: ['snail', 'animal', 'slow'] },
        { emoji: '🐞', keywords: ['ladybug', 'insect', 'animal'] },
        { emoji: '🐜', keywords: ['ant', 'insect', 'animal'] },
        { emoji: '🦟', keywords: ['mosquito', 'insect', 'animal'] },
        { emoji: '🦗', keywords: ['cricket', 'insect', 'animal'] },
        { emoji: '🕷️', keywords: ['spider', 'insect', 'animal'] },
        { emoji: '🕸️', keywords: ['spider', 'web', 'insect'] },
        { emoji: '🦂', keywords: ['scorpion', 'insect', 'animal'] },
        { emoji: '🐢', keywords: ['turtle', 'animal', 'reptile'] },
        { emoji: '🐍', keywords: ['snake', 'animal', 'reptile'] },
        { emoji: '🦎', keywords: ['lizard', 'animal', 'reptile'] },
        { emoji: '🦖', keywords: ['t-rex', 'dinosaur', 'animal'] },
        { emoji: '🦕', keywords: ['sauropod', 'dinosaur', 'animal'] },
        { emoji: '🐙', keywords: ['octopus', 'animal', 'sea'] },
        { emoji: '🦑', keywords: ['squid', 'animal', 'sea'] },
        { emoji: '🦐', keywords: ['shrimp', 'animal', 'sea'] },
        { emoji: '🦞', keywords: ['lobster', 'animal', 'sea'] },
        { emoji: '🦀', keywords: ['crab', 'animal', 'sea'] },
        { emoji: '🐡', keywords: ['blowfish', 'animal', 'sea'] },
        { emoji: '🐠', keywords: ['tropical', 'fish', 'animal', 'sea'] },
        { emoji: '🐟', keywords: ['fish', 'animal', 'sea'] },
        { emoji: '🐬', keywords: ['dolphin', 'animal', 'sea'] },
        { emoji: '🐳', keywords: ['whale', 'spout', 'animal', 'sea'] },
        { emoji: '🐋', keywords: ['whale', 'animal', 'sea'] },
        { emoji: '🦈', keywords: ['shark', 'animal', 'sea'] },
        { emoji: '🐊', keywords: ['crocodile', 'animal', 'reptile'] },
        { emoji: '🐅', keywords: ['tiger', 'animal', 'wild'] },
        { emoji: '🐆', keywords: ['leopard', 'animal', 'wild'] },
        { emoji: '🦓', keywords: ['zebra', 'animal', 'wild'] },
        { emoji: '🦍', keywords: ['gorilla', 'animal', 'primate'] },
        { emoji: '🦧', keywords: ['orangutan', 'animal', 'primate'] },
        { emoji: '🐘', keywords: ['elephant', 'animal', 'wild'] },
        { emoji: '🦛', keywords: ['hippopotamus', 'animal', 'wild'] },
        { emoji: '🦏', keywords: ['rhinoceros', 'animal', 'wild'] },
        { emoji: '🐪', keywords: ['camel', 'animal', 'desert'] },
        { emoji: '🐫', keywords: ['camel', 'animal', 'desert'] },
        { emoji: '🦒', keywords: ['giraffe', 'animal', 'wild'] },
        { emoji: '🦘', keywords: ['kangaroo', 'animal', 'wild'] },
        { emoji: '🐃', keywords: ['water', 'buffalo', 'animal'] },
        { emoji: '🐂', keywords: ['ox', 'animal', 'farm'] },
        { emoji: '🐄', keywords: ['cow', 'animal', 'farm'] }
    ],
    'Food & Drink': [
        { emoji: '🍎', keywords: ['apple', 'fruit', 'red'] },
        { emoji: '🍐', keywords: ['pear', 'fruit', 'green'] },
        { emoji: '🍊', keywords: ['tangerine', 'orange', 'fruit', 'citrus'] },
        { emoji: '🍋', keywords: ['lemon', 'fruit', 'citrus', 'yellow'] },
        { emoji: '🍌', keywords: ['banana', 'fruit', 'yellow'] },
        { emoji: '🍉', keywords: ['watermelon', 'fruit', 'summer'] },
        { emoji: '🍇', keywords: ['grapes', 'fruit', 'purple'] },
        { emoji: '🍓', keywords: ['strawberry', 'fruit', 'red'] },
        { emoji: '🫐', keywords: ['blueberry', 'fruit', 'blue'] },
        { emoji: '🍈', keywords: ['melon', 'fruit', 'green'] },
        { emoji: '🍒', keywords: ['cherry', 'fruit', 'red'] },
        { emoji: '🍑', keywords: ['peach', 'fruit', 'orange'] },
        { emoji: '🥭', keywords: ['mango', 'fruit', 'tropical'] },
        { emoji: '🍍', keywords: ['pineapple', 'fruit', 'tropical'] },
        { emoji: '🥥', keywords: ['coconut', 'fruit', 'tropical'] },
        { emoji: '🥝', keywords: ['kiwi', 'fruit', 'green'] },
        { emoji: '🍅', keywords: ['tomato', 'fruit', 'vegetable', 'red'] },
        { emoji: '🍆', keywords: ['eggplant', 'vegetable', 'purple'] },
        { emoji: '🥑', keywords: ['avocado', 'fruit', 'green'] },
        { emoji: '🥦', keywords: ['broccoli', 'vegetable', 'green'] },
        { emoji: '🥬', keywords: ['leafy', 'green', 'vegetable'] },
        { emoji: '🥒', keywords: ['cucumber', 'vegetable', 'green'] },
        { emoji: '🌶️', keywords: ['hot', 'pepper', 'spicy', 'vegetable'] },
        { emoji: '🫑', keywords: ['bell', 'pepper', 'vegetable'] },
        { emoji: '🌽', keywords: ['corn', 'vegetable', 'yellow'] },
        { emoji: '🥕', keywords: ['carrot', 'vegetable', 'orange'] },
        { emoji: '🫒', keywords: ['olive', 'fruit', 'green'] },
        { emoji: '🧄', keywords: ['garlic', 'vegetable', 'spice'] },
        { emoji: '🧅', keywords: ['onion', 'vegetable', 'spice'] },
        { emoji: '🥔', keywords: ['potato', 'vegetable', 'brown'] },
        { emoji: '🍠', keywords: ['sweet', 'potato', 'vegetable'] },
        { emoji: '🥐', keywords: ['croissant', 'bread', 'pastry', 'baked'] },
        { emoji: '🥖', keywords: ['baguette', 'bread', 'baked'] },
        { emoji: '🍞', keywords: ['bread', 'loaf', 'baked'] },
        { emoji: '🥨', keywords: ['pretzel', 'bread', 'baked', 'snack'] },
        { emoji: '🥯', keywords: ['bagel', 'bread', 'baked'] },
        { emoji: '🧀', keywords: ['cheese', 'dairy', 'food'] },
        { emoji: '🥚', keywords: ['egg', 'breakfast', 'protein'] },
        { emoji: '🍳', keywords: ['fried', 'egg', 'breakfast', 'pan'] },
        { emoji: '🧈', keywords: ['butter', 'dairy', 'spread'] },
        { emoji: '🥞', keywords: ['pancake', 'breakfast', 'sweet'] },
        { emoji: '🧇', keywords: ['waffle', 'breakfast', 'sweet'] },
        { emoji: '🥓', keywords: ['bacon', 'meat', 'breakfast'] },
        { emoji: '🥩', keywords: ['steak', 'meat', 'beef'] },
        { emoji: '🍗', keywords: ['poultry', 'chicken', 'leg', 'meat'] },
        { emoji: '🍖', keywords: ['meat', 'bone', 'pork', 'beef'] },
        { emoji: '🦴', keywords: ['bone', 'meat', 'skeleton'] },
        { emoji: '🌭', keywords: ['hotdog', 'sausage', 'bun', 'food'] },
        { emoji: '🍔', keywords: ['burger', 'hamburger', 'beef', 'food'] },
        { emoji: '🍟', keywords: ['fries', 'potato', 'fast food'] },
        { emoji: '🍕', keywords: ['pizza', 'cheese', 'food'] },
        { emoji: '🫓', keywords: ['flatbread', 'bread', 'food'] },
        { emoji: '🥙', keywords: ['stuffed', 'pita', 'wrap', 'food'] },
        { emoji: '🌮', keywords: ['taco', 'mexican', 'food'] },
        { emoji: '🌯', keywords: ['burrito', 'mexican', 'wrap', 'food'] },
        { emoji: '🫔', keywords: ['tamale', 'mexican', 'food'] },
        { emoji: '🥗', keywords: ['salad', 'vegetable', 'healthy'] },
        { emoji: '🥘', keywords: ['paella', 'pan', 'food', 'rice'] },
        { emoji: '🫕', keywords: ['fondue', 'cheese', 'pot', 'food'] },
        { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'italian', 'food'] },
        { emoji: '🍜', keywords: ['ramen', 'noodle', 'soup', 'japanese'] },
        { emoji: '🍲', keywords: ['stew', 'soup', 'bowl', 'food'] },
        { emoji: '🍛', keywords: ['curry', 'rice', 'indian', 'food'] },
        { emoji: '🍣', keywords: ['sushi', 'japanese', 'fish', 'rice'] },
        { emoji: '🍱', keywords: ['bento', 'japanese', 'box', 'food'] },
        { emoji: '🥟', keywords: ['dumpling', 'asian', 'food'] },
        { emoji: '🦪', keywords: ['oyster', 'seafood', 'shellfish'] },
        { emoji: '🍤', keywords: ['shrimp', 'seafood', 'tempura'] },
        { emoji: '🍙', keywords: ['onigiri', 'rice', 'japanese', 'food'] },
        { emoji: '🍚', keywords: ['rice', 'bowl', 'food'] },
        { emoji: '🍘', keywords: ['rice cracker', 'japanese', 'food'] },
        { emoji: '🍥', keywords: ['fish cake', 'narutomaki', 'japanese'] },
        { emoji: '🥠', keywords: ['fortune cookie', 'chinese', 'dessert'] },
        { emoji: '🥮', keywords: ['moon cake', 'chinese', 'dessert'] },
        { emoji: '🍢', keywords: ['oden', 'skewer', 'japanese', 'food'] },
        { emoji: '🍡', keywords: ['dango', 'skewer', 'japanese', 'dessert'] },
        { emoji: '🍧', keywords: ['shaved ice', 'dessert', 'cold', 'sweet'] },
        { emoji: '🍨', keywords: ['ice cream', 'dessert', 'cold', 'sweet'] },
    ],
    'Activities & Sports': [
        { emoji: '⚽', keywords: ['soccer', 'football', 'sports', 'ball'] },
        { emoji: '🏀', keywords: ['basketball', 'sports', 'ball'] },
        { emoji: '🏈', keywords: ['football', 'sports', 'ball', 'american'] },
        { emoji: '⚾', keywords: ['baseball', 'sports', 'ball'] },
        { emoji: '🥎', keywords: ['softball', 'sports', 'ball'] },
        { emoji: '🎾', keywords: ['tennis', 'sports', 'ball'] },
        { emoji: '🏐', keywords: ['volleyball', 'sports', 'ball'] },
        { emoji: '🏉', keywords: ['rugby', 'sports', 'ball'] },
        { emoji: '🥏', keywords: ['flying', 'disc', 'frisbee', 'sports'] },
        { emoji: '🎱', keywords: ['billiards', 'pool', 'sports', 'ball'] },
        { emoji: '🪀', keywords: ['yo-yo', 'toy', 'sports'] },
        { emoji: '🏓', keywords: ['ping pong', 'table tennis', 'sports', 'ball'] },
        { emoji: '🏸', keywords: ['badminton', 'sports', 'shuttlecock'] },
        { emoji: '🏒', keywords: ['ice hockey', 'sports', 'stick', 'puck'] },
        { emoji: '🏑', keywords: ['field hockey', 'sports', 'stick', 'ball'] },
        { emoji: '🥍', keywords: ['lacrosse', 'sports', 'stick', 'ball'] },
        { emoji: '🏏', keywords: ['cricket', 'sports', 'bat', 'ball'] },
        { emoji: '🪃', keywords: ['boomerang', 'sports', 'throw'] },
        { emoji: '🥅', keywords: ['goal', 'net', 'sports'] },
        { emoji: '⛳', keywords: ['golf', 'flag', 'hole', 'sports'] },
        { emoji: '🪁', keywords: ['kite', 'sports', 'wind'] },
        { emoji: '🏹', keywords: ['archery', 'bow', 'arrow', 'sports'] },
        { emoji: '🎣', keywords: ['fishing', 'sports', 'fish'] },
        { emoji: '🤿', keywords: ['diving', 'snorkel', 'sports', 'swimming'] },
        { emoji: '🥊', keywords: ['boxing', 'glove', 'sports', 'fight'] },
        { emoji: '🥋', keywords: ['martial arts', 'karate', 'judo', 'sports'] },
        { emoji: '🎽', keywords: ['running', 'sports', 'shirt', 'athletics'] },
        { emoji: '🛹', keywords: ['skateboard', 'sports', 'board'] },
        { emoji: '🛷', keywords: ['sled', 'sports', 'winter'] },
        { emoji: '⛸️', keywords: ['ice skate', 'skating', 'sports', 'winter'] },
        { emoji: '🥌', keywords: ['curling', 'stone', 'sports', 'winter'] },
        { emoji: '🎿', keywords: ['ski', 'sports', 'winter'] },
        { emoji: '⛷️', keywords: ['skier', 'skiing', 'sports', 'winter'] },
        { emoji: '🏂', keywords: ['snowboard', 'sports', 'winter'] },
        { emoji: '🪂', keywords: ['parachute', 'skydiving', 'air', 'sport'] },
        { emoji: '🏋️', keywords: ['weightlifting', 'lifting', 'gym', 'sports'] },
        { emoji: '🤼', keywords: ['wrestling', 'sports', 'fight'] },
        { emoji: '🤸', keywords: ['cartwheel', 'gymnastics', 'sports'] },
        { emoji: '⛹️', keywords: ['basketball', 'sports', 'person'] },
        { emoji: '🤺', keywords: ['fencing', 'sword', 'sports'] },
        { emoji: '🤾', keywords: ['handball', 'sports', 'ball'] },
        { emoji: '🏌️', keywords: ['golf', 'sports', 'person'] },
        { emoji: '🏇', keywords: ['horse racing', 'sports', 'horse'] },
        { emoji: '🧘', keywords: ['meditation', 'yoga', 'relax', 'sports'] },
        { emoji: '🏃', keywords: ['running', 'sports', 'person'] },
        { emoji: '🚶', keywords: ['walking', 'sports', 'person'] },
        { emoji: '🧎', keywords: ['kneeling', 'person', 'sports'] },
        { emoji: '🧍', keywords: ['standing', 'person', 'sports'] },
        { emoji: '🤳', keywords: ['selfie', 'photo', 'person'] },
        { emoji: '💃', keywords: ['dancer', 'dance', 'person'] },
        { emoji: '🕺', keywords: ['dancer', 'dance', 'person', 'man'] },
        { emoji: '👯', keywords: ['dancers', 'bunny', 'person'] },
        { emoji: '🕴️', keywords: ['levitate', 'person', 'suit'] },
        { emoji: '🚣', keywords: ['rowing', 'boat', 'sports', 'person'] },
        { emoji: '🏊', keywords: ['swimming', 'sports', 'person'] },
        { emoji: '⛹️', keywords: ['basketball', 'sports', 'person'] },
        { emoji: '🏋️', keywords: ['weightlifting', 'lifting', 'gym', 'sports'] },
        { emoji: '🚴', keywords: ['biking', 'cycling', 'sports', 'person'] },
        { emoji: '🚵', keywords: ['mountain biking', 'cycling', 'sports', 'person'] },
        { emoji: '🤸', keywords: ['cartwheel', 'gymnastics', 'sports'] },
        { emoji: '🤼', keywords: ['wrestling', 'sports', 'fight'] },
        { emoji: '🤽', keywords: ['water polo', 'sports', 'person'] },
        { emoji: '🤾', keywords: ['handball', 'sports', 'ball'] },
        { emoji: '🤹', keywords: ['juggling', 'sports', 'person'] },
        { emoji: '🧗', keywords: ['climbing', 'sports', 'person'] },
    ],
    'Travel & Places': [
        { emoji: '🚗', keywords: ['car', 'vehicle', 'travel', 'transport'] },
        { emoji: '🚕', keywords: ['taxi', 'car', 'vehicle', 'transport'] },
        { emoji: '🚙', keywords: ['suv', 'car', 'vehicle', 'transport'] },
        { emoji: '🚌', keywords: ['bus', 'vehicle', 'transport'] },
        { emoji: '🚎', keywords: ['trolleybus', 'vehicle', 'transport'] },
        { emoji: '🏎️', keywords: ['racing', 'car', 'vehicle', 'sport'] },
        { emoji: '🚓', keywords: ['police', 'car', 'vehicle', 'law'] },
        { emoji: '🚑', keywords: ['ambulance', 'vehicle', 'health'] },
        { emoji: '🚒', keywords: ['fire', 'engine', 'vehicle', 'emergency'] },
        { emoji: '🚐', keywords: ['minibus', 'vehicle', 'transport'] },
        { emoji: '🛻', keywords: ['pickup', 'truck', 'vehicle', 'transport'] },
        { emoji: '🚚', keywords: ['delivery', 'truck', 'vehicle', 'transport'] },
        { emoji: '🚛', keywords: ['articulated', 'lorry', 'truck', 'vehicle'] },
        { emoji: '🚜', keywords: ['tractor', 'vehicle', 'farm'] },
        { emoji: '🏍️', keywords: ['motorcycle', 'bike', 'vehicle'] },
        { emoji: '🛵', keywords: ['scooter', 'vehicle', 'moped'] },
        { emoji: '🚲', keywords: ['bicycle', 'bike', 'vehicle'] },
        { emoji: '🛴', keywords: ['kick', 'scooter', 'vehicle'] },
        { emoji: '🛹', keywords: ['skateboard', 'vehicle', 'sport'] },
        { emoji: '🚁', keywords: ['helicopter', 'aircraft', 'vehicle'] },
        { emoji: '✈️', keywords: ['airplane', 'plane', 'aircraft', 'flight'] },
        { emoji: '🛩️', keywords: ['small', 'airplane', 'aircraft', 'flight'] },
        { emoji: '🛫', keywords: ['departure', 'airplane', 'flight', 'airport'] },
        { emoji: '🛬', keywords: ['arrival', 'airplane', 'flight', 'airport'] },
        { emoji: '🪂', keywords: ['parachute', 'skydiving', 'air', 'sport'] },
        { emoji: '💺', keywords: ['seat', 'airplane', 'travel', 'chair'] },
        { emoji: '🚀', keywords: ['rocket', 'space', 'ship', 'vehicle'] },
        { emoji: '🛸', keywords: ['flying', 'saucer', 'ufo', 'space'] },
        { emoji: '🚉', keywords: ['station', 'train', 'railway', 'platform'] },
        { emoji: '🚊', keywords: ['tram', 'vehicle', 'railway'] },
        { emoji: '🚝', keywords: ['monorail', 'train', 'vehicle'] },
        { emoji: '🚞', keywords: ['mountain', 'railway', 'train'] },
        { emoji: '🚋', keywords: ['tram', 'car', 'vehicle', 'railway'] },
        { emoji: '🚃', keywords: ['railway', 'carriage', 'train'] },
        { emoji: '🚄', keywords: ['high-speed', 'train', 'shinkansen'] },
        { emoji: '🚅', keywords: ['bullet', 'train', 'shinkansen'] },
        { emoji: '🚈', keywords: ['light', 'rail', 'train', 'vehicle'] },
        { emoji: '🚂', keywords: ['locomotive', 'train', 'engine'] },
        { emoji: '🚆', keywords: ['train', 'car', 'vehicle', 'railway'] },
        { emoji: '🚇', keywords: ['metro', 'subway', 'underground', 'train'] },
        { emoji: '🚟', keywords: ['suspension', 'railway', 'monorail'] },
        { emoji: '🚠', keywords: ['mountain', 'cableway', 'gondola'] },
        { emoji: '🚡', keywords: ['aerial', 'tramway', 'cable', 'car'] },
        { emoji: '🛰️', keywords: ['satellite', 'space', 'communication'] },
        { emoji: '🛎️', keywords: ['bellhop', 'bell', 'service', 'hotel'] },
        { emoji: '🧳', keywords: ['luggage', 'bag', 'travel', 'suitcase'] },
        { emoji: '⌛', keywords: ['hourglass', 'time', 'sand'] },
        { emoji: '⏳', keywords: ['hourglass', 'flowing', 'time'] },
        { emoji: '⌚', keywords: ['watch', 'time', 'clock'] },
        { emoji: '⏰', keywords: ['alarm', 'clock', 'wake'] },
        { emoji: '⏱️', keywords: ['stopwatch', 'timer', 'clock'] },
        { emoji: '⏲️', keywords: ['timer', 'clock', 'kitchen'] },
    ],
    'Objects & Symbols': [
        { emoji: '⌚', keywords: ['watch', 'time', 'clock'] },
        { emoji: '📱', keywords: ['mobile', 'phone', 'cell', 'device'] },
        { emoji: '📲', keywords: ['mobile', 'phone', 'arrow', 'device'] },
        { emoji: '💻', keywords: ['laptop', 'computer', 'device'] },
        { emoji: '⌨️', keywords: ['keyboard', 'computer', 'device'] },
        { emoji: '🖥️', keywords: ['desktop', 'computer', 'device'] },
        { emoji: '🖨️', keywords: ['printer', 'device', 'office'] },
        { emoji: '🖱️', keywords: ['mouse', 'computer', 'device'] },
        { emoji: '🖲️', keywords: ['trackball', 'computer', 'device'] },
        { emoji: '🕹️', keywords: ['joystick', 'game', 'device'] },
        { emoji: '🗜️', keywords: ['clamp', 'tool', 'compress'] },
        { emoji: '💽', keywords: ['minidisc', 'storage', 'media'] },
        { emoji: '💾', keywords: ['floppy', 'disk', 'storage', 'save'] },
        { emoji: '💿', keywords: ['cd', 'disk', 'optical', 'media'] },
        { emoji: '📀', keywords: ['dvd', 'disk', 'optical', 'media'] },
        { emoji: '📼', keywords: ['vhs', 'tape', 'video', 'media'] },
        { emoji: '📷', keywords: ['camera', 'photo', 'picture'] },
        { emoji: '📸', keywords: ['camera', 'flash', 'photo'] },
        { emoji: '📹', keywords: ['video', 'camera', 'record'] },
        { emoji: '🎥', keywords: ['movie', 'camera', 'film'] },
        { emoji: '📽️', keywords: ['film', 'projector', 'movie'] },
        { emoji: '🎞️', keywords: ['film', 'frames', 'movie'] },
        { emoji: '📞', keywords: ['telephone', 'receiver', 'call'] },
        { emoji: '☎️', keywords: ['telephone', 'call', 'landline'] },
        { emoji: '📟', keywords: ['pager', 'beeper', 'message'] },
        { emoji: '📠', keywords: ['fax', 'machine', 'office'] },
        { emoji: '📺', keywords: ['television', 'tv', 'screen'] },
        { emoji: '📻', keywords: ['radio', 'music', 'broadcast'] },
        { emoji: '🎙️', keywords: ['microphone', 'studio', 'record'] },
        { emoji: '🎚️', keywords: ['level', 'slider', 'control'] },
        { emoji: '🎛️', keywords: ['control', 'knobs', 'panel'] },
        { emoji: '🧭', keywords: ['compass', 'navigation', 'direction'] },
        { emoji: '⏱️', keywords: ['stopwatch', 'timer', 'clock'] },
        { emoji: '⏲️', keywords: ['timer', 'clock', 'kitchen'] },
        { emoji: '⏰', keywords: ['alarm', 'clock', 'wake'] },
        { emoji: '🕰️', keywords: ['mantel', 'clock', 'time'] },
        { emoji: '⌛', keywords: ['hourglass', 'time', 'sand'] },
        { emoji: '⏳', keywords: ['hourglass', 'flowing', 'time'] },
        { emoji: '📡', keywords: ['satellite', 'antenna', 'signal'] },
        { emoji: '🔋', keywords: ['battery', 'power', 'energy'] },
        { emoji: '🔌', keywords: ['plug', 'electric', 'power'] },
        { emoji: '💡', keywords: ['light', 'bulb', 'idea'] },
        { emoji: '🔦', keywords: ['flashlight', 'light', 'torch'] },
        { emoji: '🕯️', keywords: ['candle', 'light', 'wax'] },
        { emoji: '🪔', keywords: ['diya', 'lamp', 'light'] },
        { emoji: '🧯', keywords: ['fire', 'extinguisher', 'safety'] },
        { emoji: '🛢️', keywords: ['oil', 'drum', 'barrel'] },
        { emoji: '💸', keywords: ['money', 'flying', 'cash'] },
        { emoji: '💵', keywords: ['dollar', 'bill', 'money'] },
        { emoji: '💴', keywords: ['yen', 'bill', 'money'] },
        { emoji: '💶', keywords: ['euro', 'bill', 'money'] },
        { emoji: '💷', keywords: ['pound', 'bill', 'money'] },
        { emoji: '💰', keywords: ['money', 'bag', 'cash'] },
        { emoji: '💳', keywords: ['credit', 'card', 'payment'] },
        { emoji: '💎', keywords: ['gem', 'diamond', 'jewel'] },
        { emoji: '⚖️', keywords: ['scales', 'justice', 'balance'] },
        { emoji: '🧰', keywords: ['toolbox', 'tools', 'kit'] },
        { emoji: '🔧', keywords: ['wrench', 'tool', 'fix'] },
        { emoji: '🔨', keywords: ['hammer', 'tool', 'build'] },
        { emoji: '⚒️', keywords: ['hammer', 'pick', 'tool'] },
        { emoji: '🛠️', keywords: ['tools', 'hammer', 'wrench'] },
        { emoji: '⛏️', keywords: ['pick', 'tool', 'mining'] },
        { emoji: '🔩', keywords: ['nut', 'bolt', 'tool'] },
        { emoji: '⚙️', keywords: ['gear', 'cog', 'settings'] }
    ]
};
