[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = ["escrow"]

[programs.localnet]
escrow = "DYuG4KZ6S1A19aXzDwFhsCDiEHB99t4WgjF5xgbbxtRZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-litesvm = "cargo test --manifest-path ./escrow/Cargo.toml --features litesvm"
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 ./escrow/tests/**/*.ts"

[test]
skip-local-validator = true
skip-deploy = true
